apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"generation":2,"labels":{"app":"watch-event-controller"},"name":"watch-event-controller","namespace":"kube-system"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"watch-event-controller"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"watch-event-controller"}},"spec":{"containers":[{"command":["watch-event-controller","-v=5"],"image":"10.10.103.59/k8s-deploy/watch-event-controller:v1.3","imagePullPolicy":"Always","name":"watch-event-controller","resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"200m","memory":"512Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","nodeSelector":{"HarmonyCloud_Status":"A"},"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}}
  generation: 7
  labels:
    app: watch-event-controller
  name: watch-event-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watch-event-controller
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: watch-event-controller
    spec:
      containers:
      - command:
        - watch-event-controller
        - -v=5
        image: k8s-deploy/watch-event-controller:v1.0
        imagePullPolicy: Always
        name: watch-event-controller
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        HarmonyCloud_Status: A
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30