kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd
  namespace: kube-system
data:
  td-agent.conf: |-
    <match fluent.**>
      type null
    </match>

    <source>
      type tail
      format none 
      path /var/log/containers/applog*/*
      pos_file /var/log/containers/es-containers-app.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ 
      tag reform.*
      read_from_head true
    </source>

    <source>
      type tail
      path /var/log/kubernetes/kubernetes-audi*
      pos_file /var/log/containers/es-kubernetes-audit.log.pos
      tag kubernetes-audit
      format json
      read_from_head true
    </source>

    <match reform.**>
      type record_reformer
      renew_record false
      enable_ruby true
      tag k8s.${tag_suffix[4]}
      <record>
        host_ip caas-dev-sys-node1
        pod_name ${tag_suffix[5].split('_')[0]}
        deploy_name ${tag_suffix[5].split('_')[0].split('-')[0..-3].join('-')}
        namespace_name ${tag_suffix[5].split('_')[1].split('.')[0]}
        container_name ${tag_suffix[6].split('.')[0]}
        container_id ${tag_suffix[7].split('.')[0]}
        logdir ${tag_suffix[9]}
        log_time ${t = Time.now; ((t.to_i * 1000000) + t.usec).to_s}
      </record>
    </match>

    <source>
      type tail
      path /var/log/containers/kube-proxy*.log
      pos_file /var/log/containers/es-kube-proxy.log.pos
      # time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kube-proxy 
      format multiline
      format_firstline /^\w\d{4}/
      format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/ 
      read_from_head true
    </source>

    <source>
      type tail
      path /var/log/containers/kube-apiserver*.log
      pos_file /var/log/containers/es-kube-apiserver.log.pos
      #time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kube-apiserver 
      format multiline
      format_firstline /^\w\d{4}/ 
      read_from_head true
      format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
    </source>

    <source>
      type tail
      path /var/log/containers/kube-controller-manager*.log
      pos_file /var/log/containers/es-kube-controller-manager.log.pos
      #time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kube-controller-manager 
      format multiline
      format_firstline /^\w\d{4}/
      format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
      read_from_head true
    </source>

    <source>
      type tail
      path /var/log/containers/kube-scheduler*.log
      pos_file /var/log/containers/es-kube-scheduler.log.pos
      #time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kube-scheduler 
      format multiline
      format_firstline /^\w\d{4}/
      format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
      read_from_head true
    </source>
   
    <source>
      type tail
      path /var/log/kubernetes/kubernetes-audi*
      pos_file /var/log/containers/es-kubernetes-audit.log.pos
      tag kubernetes-audit
      format json
      read_from_head true
    </source>

    <filter kube**>
      type record_transformer
      <record>
      host_ip caas-dev-sys-node1
      </record>
    </filter>
 
    <filter kubernetes-audit**>
      type record_transformer
      <record>
        annotations rewriteByFluentd
      </record>
    </filter>

    <match kubernetes-audit**>
      @type elasticsearch
      log_level info
      include_tag_key true
      host elasticsearch-logging
      port 9200
      #index_name kubernetes-audit-%Y.%m.%d
      logstash_format true
      logstash_prefix kubernetes-audit
      type_name auditlog
      utc_index false
    </match>

    <match **>
      type elasticsearch
      log_level info
      include_tag_key true
      host elasticsearch-logging
      port 9200
      logstash_format true
      utc_index false
      # Set the chunk limit the same as for fluentd-gcp.
      buffer_chunk_limit 2M
      # Cap buffer memory usage to 2MiB/chunk * 32 chunks = 64 MiB
      buffer_queue_limit 32
      flush_interval 5s
      # Never wait longer than 5 minutes between retries.
      max_retry_wait 30
      # Disable the limit on the number of retries (retry forever).
      disable_retry_limit
      # Use multiple threads for processing.
      num_threads 8
    </match>
