apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapi-image-claim
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: webapi-image-pv
  volumeName: webapi-image-pv