apiVersion: v1
kind: ConfigMap
metadata:
  name: webapi-cm-webxml
  namespace: kube-system
data:
  web.xml: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<web-app xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"
    xmlns=\"http://xmlns.jcp.org/xml/ns/javaee\" xmlns:websocket=\"http://www.springframework.org/schema/websocket\"
    xsi:schemaLocation=\"http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd
    http://www.springframework.org/schema/websocket http://www.springframework.org/schema/websocket/spring-websocket.xsd\"
    id=\"WebApp_ID\" version=\"3.1\">\n  <welcome-file-list>\n    <welcome-file>index.html</welcome-file>\n
    \ </welcome-file-list>\n  <context-param>\n    <param-name>contextConfigLocation</param-name>\n
    \   <param-value>classpath:applicationContext.xml </param-value>\n  </context-param>\n\n
    \ <filter>\n    <filter-name>springSessionRepositoryFilter</filter-name>\n    <filter-class>org.springframework.web.filter.DelegatingFilterProxy</filter-class>\n
    \ </filter>\n  <filter-mapping>\n    <filter-name>springSessionRepositoryFilter</filter-name>\n
    \   <url-pattern>/*</url-pattern>\n  </filter-mapping>\n  <filter>\n    <filter-name>originFilter</filter-name>\n
    \   <filter-class>com.harmonycloud.filters.OriginFilter</filter-class>\n  </filter>\n
    \ <filter-mapping>\n    <filter-name>originFilter</filter-name>\n    <url-pattern>/*</url-pattern>\n
    \ </filter-mapping>\n  <filter>\n    <filter-name>ssoFilter</filter-name>\n    <filter-class>com.whchem.sso.client.SSOFilter</filter-class>\n
    \   <init-param>\n      <param-name>SERVER_HOST</param-name>\n      <param-value>ssodev.whchem.com/uic</param-value>\n
    \   </init-param>\n    <init-param>\n      <param-name>ABSOLUTE_URL</param-name>\n
    \     <param-value></param-value>\n    </init-param>\n    <init-param>\n      <param-name>RELATIVE_URL</param-name>\n
    \     <param-value></param-value>\n    </init-param>\n    <init-param>\n      <param-name>REDIRECT_MODE</param-name>\n
    \     <param-value>FBS</param-value>\n    </init-param>\n    <init-param>\n      <param-name>LOGOUT_URI</param-name>\n
    \     <param-value>/rest/users/auth/logout</param-value>\n    </init-param>\n
    \   <init-param>\n      <param-name>EXCLUSIONS</param-name>\n      <param-value>*login*,*token*,*/system/configs/trialtime*,*/openapi/*,*/clusters,*/clusters/cache,*/testcallback*,*/tenants/addProject*,*/tenants/addUser*,*/tenants/project/addUser*,*/tenants/project/removeUser*,*/msf/tasks*,*/msf/queryInstances*,*/webhook,*/swagger-resources*,*/api-docs*,*/webjars*,*/appimages/*</param-value>\n
    \   </init-param>\n    <init-param>\n      <param-name>APP_KEY</param-name>\n
    \     <param-value>bda3b49493b7484f94eaa5e92a3e2796</param-value>\n    </init-param>\n
    \   <init-param>\n      <param-name>APP_SECRET</param-name>\n      <param-value>oZI8xeo5GFTpkivnkf+7rSPaap0=</param-value>\n
    \   </init-param>\n  </filter>\n  <filter-mapping>\n    <filter-name>ssoFilter</filter-name>\n
    \   <url-pattern>/*</url-pattern>\n  </filter-mapping>\n\n  <filter>\n    <filter-name>ssoUserFilter</filter-name>\n
    \   <filter-class>com.harmonycloud.filters.SsoFilter</filter-class>\n  </filter>\n
    \ <filter-mapping>\n    <filter-name>ssoUserFilter</filter-name>\n    <url-pattern>/*</url-pattern>\n
    \ </filter-mapping>\n\n  <filter>\n        <filter-name>DruidWebStatFilter</filter-name>
    \ \n        <filter-class>com.alibaba.druid.support.http.WebStatFilter</filter-class>
    \ \n        <init-param>  \n            <param-name>exclusions</param-name>  \n
    \           <param-value>*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*</param-value>
    \ \n        </init-param>  \n      </filter>  \n      <filter-mapping>  \n        <filter-name>DruidWebStatFilter</filter-name>
    \ \n        <url-pattern>/*</url-pattern>  \n      </filter-mapping>\n  <filter>\n
    \   <filter-name>httpFormFilter</filter-name>\n    <filter-class>com.harmonycloud.interceptors.HttpFormContentFilter</filter-class>\n
    \   <async-supported>true</async-supported>\n  </filter>\n  <filter-mapping>\n
    \   <filter-name>httpFormFilter</filter-name>\n    <servlet-name>spring</servlet-name>\n
    \ </filter-mapping>\n  <filter>\n    <filter-name>characterEncodingFilter</filter-name>\n
    \   <filter-class>org.springframework.web.filter.CharacterEncodingFilter</filter-class>\n
    \   <init-param>\n      <param-name>encoding</param-name>\n      <param-value>UTF-8</param-value>\n
    \   </init-param>\n    <init-param>\n      <param-name>forceEncoding</param-name>\n
    \     <param-value>true</param-value>\n    </init-param>\n  </filter>\n  <filter-mapping>\n
    \   <filter-name>characterEncodingFilter</filter-name>\n    <url-pattern>/*</url-pattern>\n
    \ </filter-mapping>\n  <filter>\n    <filter-name>RequestFilter</filter-name>\n
    \   <filter-class>com.harmonycloud.filters.SimpleWrappedFilter</filter-class>\n
    \ </filter>\n  <filter-mapping>\n    <filter-name>RequestFilter</filter-name>\n
    \   <url-pattern>/*</url-pattern>\n  </filter-mapping>\n  <servlet>\n    <servlet-name>spring</servlet-name>\n
    \   <servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>\n
    \   <init-param>\n      <param-name>contextConfigLocation</param-name>\n      <param-value>\n\t\t\t\tclasspath:spring-servlet.xml\n\t\t\t</param-value>\n
    \   </init-param>\n    <load-on-startup>1</load-on-startup>\n    <async-supported>true</async-supported>\n
    \ </servlet>\n  <servlet-mapping>\n    <servlet-name>spring</servlet-name>\n    <url-pattern>/rest/*</url-pattern>\n
    \   <url-pattern>/</url-pattern>\n  </servlet-mapping>\n  <listener>\n    <listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>\n
    \ </listener>\n  <listener>\n    <listener-class>org.springframework.web.context.request.RequestContextListener</listener-class>\n
    \ </listener>\n  <session-config>\n    <session-timeout>480</session-timeout>\n
    \ </session-config>\n  <security-role>\n    <role-name>r4devops</role-name>\n
    \ </security-role>\n  <security-constraint>\n    <web-resource-collection>\n      <web-resource-name>HTTPAuthServlet</web-resource-name>\n
    \     <url-pattern>/rest/msf/queryInstances</url-pattern>\n      <url-pattern>/rest/msf/tasks/*</url-pattern>\n
    \     <url-pattern>/rest/cicdjobs/stage/*/result/*/testcallback</url-pattern>\n
    \     <url-pattern>/rest/tenants/addProject</url-pattern>\n      <url-pattern>/rest/tenants/addUser</url-pattern>\n
    \     <url-pattern>/rest/tenants/project/addUser</url-pattern>\n      <url-pattern>/rest/tenants/project/removeUser</url-pattern>\n
    \     <http-method>DELETE</http-method>\n      <http-method>GET</http-method>\n
    \     <http-method>POST</http-method>\n      <http-method>PUT</http-method>\n
    \   </web-resource-collection>\n    <auth-constraint>\n      <role-name>r4devops</role-name>\n
    \   </auth-constraint>\n  </security-constraint>\n  <login-config>\n    <auth-method>BASIC</auth-method>\n
    \   <realm-name>Default</realm-name>\n  </login-config>\n</web-app>\n"
