apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    nephele/user: gao
  name: webapi
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - image: 10.10.124.151/library/k8s-webapi:qas
        resources:
          limits:
            cpu: 2000m
            memory: 4096Mi
          requests:
            cpu: 500m
            memory: 1024Mi
        imagePullPolicy: Always
        env:
        - name: "JAVA_OPTS"
          value: "-Xmx4096m"
        - name: "logpilot_logs_logstash"
          value: "/opt/logs/*"
        - name: "logpilot_logs_logstash_tags"
          value: "k8s_resource_type=Deployment,k8s_resource_name=webapi"
        name: webapi
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/local/k8s-mars-api/WEB-INF/classes/constant.properties 
          subPath: constant.properties
          name: webapi-config-volume
        - mountPath: /usr/local/k8s-mars-api/WEB-INF/web.xml
          subPath: web.xml
          name: webapi-cm-webxml-volume
        - mountPath: /usr/local/k8s-mars-api/fsfiles
          name: webapi-storage
        - mountPath: /var/run
          name: docker
        - mountPath: /opt/logs
          name: logdirwebapi
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /rest/clusters
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      nodeSelector:
        HarmonyCloud_Status: A
      volumes:
      - configMap:
          name: webapi-config
          items:
          - key: constant.properties
            path: constant.properties
        name: webapi-config-volume
      - configMap:
          name: webapi-cm-webxml
          items:
          - key: web.xml
            path: web.xml
        name: webapi-cm-webxml-volume
      - name: webapi-storage
        persistentVolumeClaim:
          claimName: webapi-claim
      - name: docker
        hostPath:
          path: /var/run
      - name: logdirwebapi
        emptyDir: {}
