apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    nephele/user: gao
  name: webapi
  namespace: kube-system
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - image: 10.10.124.151/library/k8s-webapi:dev
        resources:
          limits:
            cpu: 2000m
            memory: 4096Mi
          requests:
            cpu: 1000m
            memory: 2048Mi
        imagePullPolicy: Always
        env:
        - name: "JAVA_OPTS"
          value: "-Xmx4096m"
        name: hc
        ports:
        - containerPort: 8080 
          hostPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/local/k8s-mars-api/WEB-INF/classes/constant.properties 
          subPath: constant.properties
          name: webapi-config-volume
        - mountPath: /tmp
          name: tmp
        - mountPath: /var/run
          name: docker
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      nodeSelector:
        HarmonyCloud_Status: A
      volumes:
      - configMap:
          name: webapi-config
          items:
          - key: constant.properties
            path: constant.properties
        name: webapi-config-volume
      - name: tmp
        hostPath:
          path: /tmp
      - name: docker
        hostPath:
          path: /var/run
