apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    nephele/user: gao
  name: webapi
  namespace: kube-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - image: library/k8s-webapi:prd
        resources:
          limits:
            cpu: 4000m
            memory: 8192Mi
          requests:
            cpu: 1000m
            memory: 2048Mi
        imagePullPolicy: Always
        env:
        - name: "JAVA_OPTS"
          value: "-Xmx8192m"
        name: webapi
        ports:
        - containerPort: 8080
          hostPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/local/k8s-mars-api/WEB-INF/classes/constant.properties
          subPath: constant.properties
          name: webapi-config-volume
        - mountPath: /home
          name: webapi-storage
        - mountPath: /var/run
          name: docker
        - mountPath: /opt/logs
          name: logdirwebapi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      nodeSelector:
        HarmonyCloud_Status: A
      volumes:
      - configMap:
          name: webapi-config
          items:
          - key: constant.properties
            path: constant.properties
        name: webapi-config-volume
      - name: webapi-storage
        persistentVolumeClaim:
          claimName: webapi-claim
      - name: docker
        hostPath:
          path: /var/run
      - name: logdirwebapi
        emptyDir: {}
