apiVersion: v1
kind: Pod
metadata:
  labels:
    debug: proxy
    app: servicename-debug
  name: debug-proxy-username
  namespace: {namespace}
spec:
  containers:
  - command:
    - /usr/sbin/sshd
    - -D
    image: /local
    imagePullPolicy: IfNotPresent
    name: proxy
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: admin-secret
  restartPolicy: Always
  schedulerName: default-scheduler
