angular.module('mainApp')
.config(['$translateProvider',function($translateProvider){
	// $translateProvider.useSanitizeValueStrategy('sanitize');

	$translateProvider.translations('ch',{
		// index page
		'Service': '服 务',
		'Storage': '存 储',
		'Image': '镜 像',
		'Router': '路 由',
		// 'service': '服务',
		'storage': '存储',
		'volumes':'存储',
		'imagetitle':'镜像',
		'image': '镜像',
		'router': '路由' ,
		'warning': '近期警告' ,
		'setting': '设置',
		'logout': '退出',
		'notification': '通知',
		'close': '关闭',
		'notNotification': '暂无通知',
		'confirm': '确定',
		'login': '登录',
		'chooseTrans':'switch to English',
		'chooseTenant':'请选择租户',
		'chooseNamespace':'请选择项目',
		'tenant':'租户',
		'cloud':'云端',
		'Gateway':'应用网关',

		// serviceAll page
		'serviceList':'服务列表',
		'new':'创建',
		'operate':'操作',
		'start':'启 动',
		'stop':'停 止',
		'deleteText':'确定删除吗？',
		'delete':'删 除',
		'searchText':'请输入服务器名称或标签进行搜索,不同标签用，隔开',
		'name':'名称',
		'namespace':'项目名',
		'state':'状态',
		'label':'标签',
		'serviceIP':'服务地址',
		'version':'版本',
		'instanceCount':'服务实例',
		'startTime':'创建时间',
		'stopped':'已停止',
		'started':'已启动',
		'stopping':'停止中',
		'starting':'启动中',
		'none':'无',
		'detail':'查看',

		// storageAll page
		'storageList':'存储列表',
		'deleteStorage':'确定删除服务吗？',
		'capacity':'容量',
		'usageState':'使用状态',
		'bound':'可用',
		'pending':'等待',
		'lost':'丢失',
		'noBindService':'无绑定服务',

		//routerAll page
		'httpProxy':'HTTP应用网关',
		'entrance':'入口',
		'urlPattern':'入口',
		'port':'端口',
		'tcpProxy':'TCP/UDP应用网关',
		'targetPort':'目标端口',
		'proxy':'协议',
		'protocol':'协议',

		//userAll page
		'usersList':'用户列表',
		'Sure to delete':'确定删除用户吗?',
		'username':'用户名',
		'realname':'真实用户名',
		'email':'用户邮箱',
		'createtime':'创建时间',
		'rolename':'角色',
		'roleName':'镜像权限',
		'rolebind':'镜像信息',
		'project':'项目名称',
		'updateUser':'修改密码',
		'oldPassword':'旧密码',
		'newPassword':'新密码',
		'update':'修改',
		'commit':'提交',
		'saveUser':'保存',
		'refresh':'更新',

		//autoFlex page
		'targetCpuUsage':'目标CPU占用率',
		'instanceRange':'当前数量范围',
		'nowInatanceNum':'当前实例数量',
		'nowCpuUsage':'当前CPU占用',
		'autoflexTime':'最近伸缩时间',
		'closeAutoflex':'关闭自动伸缩',
		'closeAutoflexText':'确定关闭自动伸缩？',
		'noAutoflexEvent':'暂时没有伸缩事件出现',

		//chooseFlex page
		'autoflexConfig':'自动伸缩配置',
		'minInstance':'当前数量范围下限',
		'maxInstance':'当前数量范围上限',

		//choosePod page
		'Console':'控制台',
		'openConsole':'打开控制台',
		'choosePod':'选择pod',
		'chooseContainer':'选择容器',
		'getConsoleInformation':'获取控制台链接',

		//confirm page
		'no':'取消',
		'yes':'确定',

		//event page
		'noEvent':'暂时没有事件出现',

		//modifyContainer page
		'modifyContainer':'修改容器',
		'conatinerName':'容器名称',
		'fillInContainerName':'请填写容器名称',
		'wrongContainerName':'错误的容器名称',
		'chooseImage':'选择镜像',
		'fillInImage':'请补全镜像信息',
		'memory':'内存配额',
		'cpuValue':'CPU权重',
		'portConfig':'端口配置',
		'fillInPort':'请输入端口',
		'fillInProtocol':'请输入对应协议',
		'wrongPort':'错误的端口范围',
		'portDuplicatePort':'与当前容器中的其他端口重复',
		'portDuplicateContainer':'与其他容器中的端口重复',
		'command':'执行命令',
		'fillInCommand':'请输入命令',
		'args':'执行参数',
		'fillInArgs':'请输入参数',
		'env':'环境变量',
		'inputEnvKey':'环境变量的key',
		'inputEnvValue':'环境变量的value',
		'constantStorage':'持久化存储',
		'mount':'挂载',
		'inputMount':'请输入挂载点',
		'chooseVolume':'请选择存储卷',
		'readOnly':'只读',
		'wrongMount':'错误的挂载点格式,请以/xxx的格式输入',
		'gitStorage':'git存储',
		'inputGitUrl':'请输入git地址',
		'inputRevision':'请输入revision',
		'wrongGitUrl':'错误的git地址格式,请以url的格式输入',
		'deleteContainer':'删除容器',
		'deleteContainerText':'确定删除该容器？',
		'save':'保存',
		'pathDuplicate':'与其他存储的挂载点重复',
		'fillInVolume':'请补全存储配置',

		//newContainer page
		'newContainer':'添加容器',
		'saveContainer':'添加容器',
		'Input Name':'输入名称',
		'chooseHarbor':'选择镜像库',
		'Config More':'更多',
		'Config Less':'更少',
		'Collapse':'收起',
		'ConfigMap':'配置文件',
		'inputConfigPath':'请输入配置文件保存路径',
		'inputConfigValue':'请输入配置文件内容',
		'inputConfigName':'请输入配置文件名称',
		'fillInInitialDelaySeconds':'首次检查延时时间',
		'fillInTimeoutSeconds':'检查超时时间',
		'fillInPeriodSeconds':'检查间隔时间',
		'fillInSuccessThreshold':'成功阈值',
		'fillInFailureThreshold':'失败阈值',

		//modifyRouter page
		'modifyRouter':'修改路由规则',
		'annotation':'备注',

		//monitorChart page
		'container':'容器',
		'time':'时间',
		'thirtyMinute':'30分钟以内',
		'sixHour':'6小时以内',
		'twentyFourHour':'24小时以内',
		'sevenDay':'7天以内',
		'thirtyDay':'30天以内',
		'setupToNow':'从创建开始至今',
		'createMonitor':'正在生成监控数据,请耐心等待...',
		'process':'组件',

		//newIng page
		'Httprouter':'HTTP应用网关',
		'Tcprouter':'TCP应用网关',
		'newProxy':'新建代理',
		'addTCPRouter':'新建TCP应用网关',
		'addHTTPRouter':'新建HTTP应用网关',
		'fillInName':'请填写名称',
		'fillInNamespace':'请填写项目',
		'hostName':'Host名称',
		'HostName':'主机名称',
		'chooseService':'请选择服务',
		'targetService':'目标服务',
		'saveProxy':'新建代理',
		'fillInPath':'请输入路径,例如:/文件名',
		'subDomain':'名称',
		'domain':'域名',
		'urlMap':'URL映射',

		//newLb page
		'fillInPicker':'请填写选择器',
		'portRange':'端口(20000-20670)',
		'protocolType':'协议类型',
		'selector':'Node选择',
		'portMap':'端口映射',

		//podContainer page
		'refreshConfig':"更新配置",
		'runState':'运行状态',
		'containerRestart':'容器重启次数',
		'containerState':'容器状态',
		'restartTime':'重启次数',
		'readOnlyYes':'是',
		'readOnlyNo':'否',
		'log':'日志',
		'storagePath':'挂载路径',
		'wrongPath':'错误的挂载路径格式',
		'gitUrl':'git地址',

		//podInformation page
		'activeTime':'启动时间',
		'podActiveTime': '创建时间',
		'containerCount':'容器数量',
		'IP':'IP地址',
		'nodeIP':'节点地址',
		'creationTime':'创建时间',

		//podInstance page
		'Pods':'Pods',
		'internelIP':'内网地址',
		'podClusterIP':'服务地址',
		'internalDomain':'服务域名',
		'podIP':'Pod地址',
		'running':'运行',
		'pause':'暂停',

		//serviceDetail page
		'autoflex':'自动伸缩',
		'terminating':'终止',
		'waiting':'等待',
		'VolumeMounts':'卷挂载',
		'pod':'Pod',
		'ChangeConfigValue':'修改配置文件内容',
		// 'EditValue':'Edit Value',

		//serviceInformation page
		'refershTime':'更新时间',
		'internelPort':'内部端口',
		'Owner':'拥有者',
		'Version': '版本',
		'ContainerStatus': '容器状态',
		'Specs':'容器配置',
		'configName':'配置文件名称',
		'configValue':'配置文件内容',

		//serviceNew page
		'newService':'创建服务',
		'serviceName':'服务名称',
		'fillInServiceName':'请填写服务名称',
		'wrongServiceName':'错误的服务名称格式',
		'labelText':'请以a=b的形式填写,不同的label用,隔开',
		'wrongLabel':'错误的label格式',
		'session':'保持会话',
		'containerList':'容器列表',
		'config':'配置',
		'add':'创建',
		'fillInInternelIP':'请输入服务地址',
		'wrongIP':'错误的内部IP格式,IP上限为:255.255.255.255',
		'saveService':'创建服务',
		'inputSelectorKey':'请输入选择标签的key',
		'inputSelectorValue':'请输入选择标签的value',

		//warninglist page
		'related':'关联对象',

		//setting page
		'username':'用户名',
		'password':'密码',
		'serviceAndPod':'服务/pod',
		'deleting':'删除中...',
		'creating':'新建中...',
		'modifypassword':'修改密码',

		//storageDetail page
		'serviceHost':'服务器',
		'newStorage':'新建存储',
		'storageName':'存储名称',
		'saveStorage':'创建存储',
		'fillInStorageName':'请填写存储名称',
		'wrongStorageName':'错误的存储名称格式',
		'path':'路径',

		//imageAll page 
		'downAndUpload':'上传与下载',
		'author':'作者',
		'loading':'载入中...',
		'deployImage':'点击以部署镜像',

		//upload page
		'downloadImage':'下载镜像',
		'downloadStep1':'在本地 docker 环境中输入以下命令，就可以pull一个镜像到本地了。',
		'downloadStep2':'注意：为了在本地方便使用，下载后您可以修改tag成短标签，比如',
		'pushImage':'发布镜像',
		'stepOne':'1. 在本地 docker 环境中输入以下命令进行登录。',
		'stepTwo':'2. 假如在本地已经有了想要push的image,比如这个image名为hello-world。如果在本地没有image,可以首先从Docker官方网站去pull一个下来。',
		'stepThree':'3. 然后，需要对这个image进行标记，在命令中输入：',
		'stepFour':'4. 最后在命令行输入如下命令就可以push这个image到你创建的镜像仓库中了。',

		'repository':'自定义仓库名',

		//editInstance page
		'inputInstance':'请填写实例',
		'instanceMustNumber':'实例数量必须为数字',
		'instanceMustLagerOne':'实例数量必须大于1',

		//podDetaileController psge
		'BasicInfo':'基本信息',
		'AdvanceInfo':'更多信息',
		'basicInformation':'基本信息',
		'podInformation':'基本信息',
		'monitor':'监控',
		'podInstance':'pod实例',
		'event':'事件',
		'logInformation':'日志信息',
		'logdir':'日志文件',

		//myTenant page
		'basicTanInformation':'租户基本信息',
		'namespaceInformation':'项目信息',
		'roleInformation':'角色信息',
		'networkInformation':'网络信息',
		'harborInformation':'镜像库信息',
		'adminInformation':'管理人员',
		'deletemessage':'确定要删除吗?',
		'mytenantname':'租户名称',
		'mytenantadmin':'租户管理员',
		'comment':'备注',
		'adminsname':'管理员名称',
		'addtime':'加入时间',
		'harborname':'镜像名称',
		'harbortype':'镜像类型',
		'namespacename':'项目名称',
		'networkname':'网络名称',

		//confirm related
		'serviceError':'服务端异常',
		'serviceErrorText':'系统出了点小问题，请稍后重试！',
		'inputError':'输入错误',
		'inputCommand':'请输入执行命令',
		'inputArgs':'请输入执行参数',
		'inputEnv':'请补全环境变量',
		'inputStorage':'请补全挂载配置',
		'storageDuplicate':'重复的挂载路径',
		'atLeastOnPort':'请输入至少一条端口配置',
		'nameDuplicate':'重名错误',
		'conatinerNameDuplicate':'该容器与其他容器重名',
		'serviceNameDuplicate':'该服务与同一项目下的其他服务重名',
		'noServiceError':'未选择服务',
		'selectServiceError':'请选择需要操作的服务',
		'giveUpService':'确定放弃新建服务？',
		'giveUpConfig':'确定放弃保存配置？',

		'namespaceDuplicate':'与现有项目重复！',
		'userDuplicate':'与现有用户重复！',

		'newFail':'新建失败！',
		'inputNamespace':'请输入项目名称！',
		'deleteNamespaceService':'请先删除该项目下的应用，再尝试删除！',
		'deleteFail':'删除失败！',

		'noStorageError':'未选择存储',
		'selectStorageError':'请选择需要操作的存储',
		'storageNameDuplicate':'该服务与同一项目下的其他存储重名',

		'hostaddress':'入口域名：',
		'entranceip':'入口IP：',
		'Internal Virtual Port':'内部虚拟端口',
		'Service Port':'服务端口',
		'virtualPort': '虚拟端口',
		'podPort': 'Pod端口',
		'containerPort': '容器端口',

		'livenessProbe': 'Liveness Probe',
		'readinessProbe': 'Readiness Probe',
		'fillInProbe': '请补全probe配置',

		// user Authorization
		'userAuthorization': '用户授权',
		'role':'Role',
		'roleBinding':'Role Binding',
		'type': '类型',
		'bindingCount':'绑定数量',
		'newRole':'新建Role',
		'resource':'Resource',
		'noneResource':'None Resource',
		'saveRole':'Save',
		'user':'用户',
		'clusterrole':'Cluster role',
		'clusterroleBinding': 'Cluster RoleBinding',
		'newRoleBinding':'新建RoleBinding',
		'newCRoleBinding':'新建Cluster RoleBinding',
		'source':'Source',
		'priority':'优先级',

		//menu
		'Overview':'看板',
		'Dashboard':'仪表盘',
		'Application':'应用',
		'UserManage':'用户管理',
		'Usermanage':'用户管理',
		'OperationAudit':'操作审计',
		'Tenet':'租户',
		'Tenetmanage':'租户管理',
		'Mytenet':'我的租户',
		'Myproject':'我的项目',
		'Authorize':'权限管理',
		'Role':'角色',
		'Rolebinding':'角色绑定',
		'Softinfrastructure':'应用基础设施',
		'Menunode':'Node',
		'Project':'项目',
		'Menunetwork':'网 络',
		'Menuharbor':'镜 像',
		'Cloudplatform':'云平台',
		'Component':'集群组件',
		'KubeProxy':'KubeProxy',
		'Scheduler':'Scheduler',
		'Ctrlmanage':'Controller Management',
		'Apiserver':'Api Server',
		'Kubelet':'Kubelet',
		'Docker':'Docker',
		'Etcd':'Etcd',
		'Extension':'扩展组件',
		'Influxdb':'InfluxDB',
		'Harbor':'Harbor',
		'Elasticsearch':'Elastic Search',
		'HAproxy':'HAproxy',
		'Initial':'初始化中心',

		//tenant
		'Tenantname':'租户名称',
		'Tenantlist':'租户列表',
		'Admin':'管理员',
		'tenantInformation':'基本信息',
		'Network':'网络',
		'Harbor':'镜像库',
		'Volume':'存储卷',
		'Member':'成员',
		'Networkname':'网络名称',
		'Harborname':'镜像库名称',
		'Volumename':'存储卷名称',
		'Username':'用户名称',
		'RealName':'真实姓名',
		'Add User To Tenant':'新建用户',
		'Create Volume For Tenant':'新建存储',
		'Create Repo Group For Tenant':'新建镜像库',
		'Add Tenant':'新建租户',
		'NetworkCount':'网络数量',
		'ProjectCount':'项目数量',
		'RepoGroupCount':'镜像库数量',
		'Project Overview':'项目概览',
		'By Service':'服务数量分布',
		'By Member':'成员数量分布',
		'Edit':'编辑',
		'tenantResource':'租户资源',

		//project 
		'projectInformation':'基本信息',
		'CreateProject':'新建项目',
		'BasicConfig':'基本配置',
		'Subnet':'子网',
		'ResourceQuota':'资源配置',
		'ChangeProject':'修改项目',
		'HarborMember':'镜像库权限',
		'netname':'网络',
		'Subname':'子网名称',
		'subbind':'子网绑定',

		'Multiple':'多重挂载',
		'Usage':'使用情况',
		'Provider':'提供商',
		'Add User To Project':'向项目中添加用户',
		'Add User To Repo Group':'向镜像库中添加用户',

		'subnetName':'子网',
		'addsubnet':'新增子网',


		//node
		'harborList':'镜像库列表',
		'tenantName':'镜像名称',
		'networkList':'网络',
		'readOnlyTrue':'是',
		'readOnlyFalse':'否',
		'PodStatus':'Pod状态',
		'architecture':'架构',
		'os':'操作系统',
		'kernelVersion':'内核版本',
		'kubeProxyVersion':'kube-proxy版本',
		'kubeletVersion':'kubelet版本',
		'Success':'成功',
		'Label Edit Success':'标签修改成功!',
		'Error':'错误',
		'inputLabelKey':'请输入标签的key',
		'inputLabelValue':'请输入标签的value',
		'nodeInfo':'Node详情',
		'Ready':'就绪',
		'OutOfDisk':'磁盘已满',
		'MemoryPressure':'内存将满',

		//network
		'createNetwork':'新建网络',
		'networkName':'网络名称',
		'subnet':'子网',
		'noNetworkError':'网络未选择',
		'selectNetworkError':'请选择要删除的网络',
		'noHarborError':'存储未选择',
		'selectHarborError':'请选择要删除的存储',
		'noVolumeError':'镜像未选择',
		'selectVolumeError':'请选择要删除的镜像',

		//tenant module error text
		'fillInTenantName':'请输入租户名称',
		'wrongTenantName':'错误的租户名称',
		'fillInNetworkName':'请输入网络名称',
		'wrongNetworkName':'错误的网络名称',
		'fillInProjectName':'请输入项目名称',
		'wrongProjectName':'错误的项目名称',
		'fillInHarborName':'请输入镜像库名称',
		'wrongHarborName':'错误的镜像库名称',
		'fillInVolumeName':'请输入存储名称',
		'wrongVolumeName':'错误的存储名称',

		//harbor and repo and tag
		'total':'镜像总数',
		'insecurity':'高危镜像',
		'mild':'温和镜像',
		'security':'安全镜像',
		'not support':'不支持镜像',
		'abnormal':'异常镜像',
		'high':'高危漏洞',
		'other':'其他漏洞',
		'package':'包维度',
		'vulnerability':'漏洞维度',
		'VulnerabilitleName':'漏洞名称',
		'PackageName':'包名称',
		'PackageVersion':'包版本',
		'HighLevel':'高危漏洞',
		'MediumLevel':'中危漏洞',
		'LowLevel':'低危漏洞',
		'NegligibleLevel':'可忽略漏洞',
		'UnknowLevel':'未知漏洞',
		'Level':'漏洞级别',
		'CurrentVersion':'当前版本',
		'FixedVersion':'修复后版本',
		'ImageLayer':'镜像层',
		'imageAnalyze':'镜像安全分析',
		'Total Number of Vulnerabilitles':'漏洞总数量',
		'Vulnerabilitles can be Repaired':'可修复漏洞数量',
		'Number of High Risk vulnerabilitle(s)':'高危漏洞数量',
		'Number of Medium Risk vulnerabilitle(s)':'中危漏洞数量',
		'Number of Low Risk vulnerabilitle(s)':'低危漏洞数量',
		'Number of Negligible Risk vulnerabilitle(s)':'可忽略漏洞数量',
		'Number of Unknow vulnerabilitle(s)':'未知漏洞数量',
		'can be repaired':'可以被修复',
		'no repo':'暂时没有镜像',

		//user
		'fillInEmailName':'请填写邮箱!',
		'wrongEmailName':'错误的邮箱格式!',
		'fillInUserName':'请填写用户名称',
		'wrongUserName':'错误的用户名称格式',
		'userNameDuplicate':'此用户已存在!',
		'emailDuplicate':'邮箱重名',
		'EmailDuplicate':'此邮箱已存在',
		'noUserError':'没有选择用户',
		'selectUserError':'请选择至少一个用户',
		'fillInPassword':'密码输入错误',
		'wrongPassword':'输入的密码必须包含大小写字母和数字',
		'wrongPasswordLength':'密码长度必须大于7!',
		'fillPassword':'密码长度',
		'WrongPassword':'密码不能包含特殊字符',
		'addUser':'新建用户',


		//extend
		'monitorProviderList':'监控供应商',
		'imageProviderList':'镜像供应商',
		'logProviderList':'系统日志',
		'loadBalancerProviderList':'负载平衡器供应商',
		'storageProviderList':'存储供应商',
		'networkProviderList':'网络供应商',
		'ClusterComponentList':'集群组件',
		'address':'地址',
		'host':'主机地址',
		'lastUpdateTime':'最后更新时间',
		'logmessageon':'日志告警已开启',
		'logmessageoff':'日志告警未开启',
		'monitoron':'监控告警已开启',
		'monitoroff':'监控告警未开启',
		'goset':'去设置',
		'gooppen':'去开启',
		'isLogMonit':'日志监控',
		'logMonitSeverity':'日志监控类型',
		'restartMonit':'重启监控',
		'alarmType':'报警类型',
		'alarmRules':'报警规则',
		'alarmSetting':'报警设置',
		'measurement':'测量',
		'threshold':'阈',
		'Actions':'操作',
		'logboth':'警告和错误日志',
		'onglog':'仅错误日志',
		'SMTPServer':'SMTP服务器',

		//infras
		'LogWarningTurnedOn':'日志告警已开启',
		'LogWarningClosed':'日志告警未开启',
		'goConfig':'去设置',
		'goOpen':'去开启',
		'MonitorAlarmsTurnedOn':'监控告警已开启',
		'MonitorAlarmsClosed':'监控告警未开启',
		'nodeList':'Node列表',
		'ConfigLogAlarm':'设置日志告警',
		'OpenLogAlarm':'开启日志告警',
		'OpenLogMonitor':'开启监控告警',
		'ConfigLogMonitor':'设置监控告警',

		// Dashboard page
		'CPU':'CPU',
		'Memory':'内存',
		'Coworkers':'协作者',
		'DeploymentCountByUser':'各用户服务数量',
		'DeploymentCount':'服务数量',
		'Secure Image Count':'安全镜像',
		'Abnormal Image Count':'异常镜像',
		'Total Image Count':'镜像总数',
		'Insecure Image Count':'不安全镜像',
		'Un-scannable Image Count':'不可扫描镜像',
		'Image Count By User':'各用户镜像数量',
		'Insecure Image Count By User':'各用户不安全镜像数量',
		'System Warning':'系统告警',
		'Recent Events':'近期事件',
		'Pod Usage':'Pod使用量',
		'CPU Usage':'CPU使用量',
		'Memory Usage':'内存使用量',
		'Disk Usage':'磁盘使用量',
		'Current Usage':'当前使用量',
		'Can Be Created':'可以被创建',
		'Kubernetes Version':'Kubernetes版本',
		'ETCD Version':'ETCD版本',
		'Docker Version':'Docker版本',
		'Neutron Version':'Neutron版本',
		'Calico Version':'Calico版本',
		'Infrastructure':'基础设施',
		'Host':'主机',
		'CPU Core':'CPU核数',
		'System Component Status':'系统组件状态',
		'Tenants':'租户',
		'Tenant Project Usage Rate':'各租户中项目占比',
		'Tenant Image Usage Rate':'各租户中镜像占比',
		'Can be Used':'可用',
		'In this Project':'在当前项目中',

		//log
		'output':'标准输出',
		'logout':'日志文件输出',
		'logOutput':'日志来源',

		//user audit
		'userAudit':'用户审计',
		'operation':'操作',
		'module':'模块',
		'params':'参数',
		'accessTime':'操作时间',
		'url':'URL',
		'accessUser':'用户名',
		'accessNamespace':'项目名',
		'accessTenantName':'租户名',
		'search':'搜索',

		//initial
		'Admin Initial':'管理员',
		'Cluster Role Initial':'角色',
		'Machine Account Initial':'机器账号',
		'Reset To Default':'设置到默认值',

	});

	$translateProvider.translations('en',{
		// index page
		'Service': 'Service',
		'Storage': 'Storage',
		'Image': 'Image',
		'Router': 'Router',
		// 'service': 'Service',
		'storage': 'Volume',
		'volumes': 'Volume',
		'imagetitle': 'IMAGE',
		'image': 'Image',
		'router': 'Router' ,
		'warning': 'Warning' ,
		'setting': 'Setting',
		'logout': 'Logout',
		'notification': 'Notification',
		'close': 'Close',
		'notNotification': 'No Notification',
		'confirm': 'Confirm',
		'login': 'Login',
		'chooseTrans':'切换为中文',
		'chooseTenant':'Please Choose Tenant',
		'chooseNamespace':'Please Choose Project',
		'tenant':'Tenant',
		'cloud':'Cloud',
		'Gateway':'Gateway',

		// serviceAll page
		'serviceList':'Service List',
		'new':'Create',
		'operate':'Actions',
		'start':'Start',
		'stop':'Stop',
		'deleteText':'Are You Sure to Delete?',
		'delete':'Delete',
		'searchText':'search with service name or label',
		'name':'Name',
		'namespace':'Project',
		'state':'State',
		'label':'Label',
		'serviceIP':'Internal IP',
		'version':'Version',
		'instanceCount':'Service Instance',
		'startTime':'Active Time',
		'stopped':'Stopped',
		'started':'Running',
		'stopping':'Stopping',
		'starting':'Starting',
		'none':'N/A',
		'detail':'about detail',

		// storageAll page
		'storageList':'Storage List',
		'deleteStorage':'Are You Sure to Delete?',
		'capacity':'Capacity',
		'usageState':'Usage State',
		'bound':'bound',
		'pending':'pending',
		'lost':'Lost',
		'noBindService':'no service',

		//routerAll page
		'httpProxy':'HTTP Gateway',
		'entrance':'Entrance',
		'urlPattern':'URL Pattern',
		'port':'Port',
		'tcpProxy':'TCP/UDP Gateway',
		'targetPort':'Target Port',
		'proxy':'Proxy',
		'protocol':'Protocol',

		//userAll page
		'usersList':'User List',
		'Sure to delete':'Are You Sure To Delete?',
		'username':'User ID',
		'realname':'Real Name',
		'email':'Email',
		'createtime':'Creation Time',
		'rolename':'Role',
		'roleName':'Repo Permissions',
		'rolebind':'Repo Group',
		'project':'Project',
		'updateUser':'Change Password',
		'oldPassword':'Old Password',
		'newPassword':'New Password',
		'update':'update',
		'commit':'Commit',
		'saveUser':'Save',
		'refresh':'Refresh',

		//autoFlex page
		'targetCpuUsage':'Target CPU Usage',
		'instanceRange':'Instance Range',
		'nowInatanceNum':'Instane',
		'nowCpuUsage':'Current CPU Usage',
		'autoflexTime':'Last Autoscaling Time',
		'closeAutoflex':'Disable Autoscaling',
		'closeAutoflexText':'Sure To Close autoscaling？',
		'noAutoflexEvent':'no autoscaling event',

		//chooseFlex page
		'autoflexConfig':'Autoscaling Config',
		'minInstance':'Min Instance Count',
		'maxInstance':'Max Instance Count',

		//choosePod page
		'Console':'Console',
		'openConsole':'Open Console',
		'choosePod':'Pod',
		'chooseContainer':'Container',
		'getConsoleInformation':'Get Console Link',

		//confirm page
		'no':'Cancel',
		'yes':'Confirm',

		//event page
		'noEvent':'no event',

		//modifyContainer page
		'modifyContainer':'Modify Conatiner',
		'conatinerName':'Container Name',
		'fillInContainerName':'please fill in container name',
		'wrongContainerName':'container name illegal',
		'chooseImage':'Image',
		'fillInImage':'please fill in image',
		'memory':'Memory Quota',
		'cpuValue':'CPU Weight',
		'portConfig':'Port',
		'fillInPort':'input port',
		'fillInProtocol':'please input protocol',
		'wrongPort':'invalid port range',
		'portDuplicatePort':'port same with port in this container',
		'portDuplicateContainer':'port same with port in other container',
		'command':'Command',
		'fillInCommand':'please input command',
		'args':'Args',
		'fillInArgs':'please input args',
		'env':'Env',
		'inputEnvKey':'input key of environment variable',
		'inputEnvValue':'input val of environment variable',
		'constantStorage':'Volume',
		'mount':'mount',
		'inputMount':'please input mount',
		'chooseVolume':'please choose volume',
		'readOnly':'Read Only',
		'wrongMount':'wrong mount,please input as "/xxx"',
		'gitStorage':'Git Volume',
		'inputGitUrl':'please input git url',
		'inputRevision':'please input revision',
		'wrongGitUrl':'wrong git url,please input as url format',
		'deleteContainer':'Delete',
		'deleteContainerText':'Sure To Delete Container?',
		'save':'Save',
		'pathDuplicate':'same with path in other volumes',
		'fillInVolume':'please fill in volume config',


		//newContainer page
		'newContainer':'Add Container',
		'saveContainer':'Save',
		'Input Name':'Input Name',
		'chooseHarbor':'Repo Group',
		'Config More':'More',
		'Config Less':'Less',
		'Collapse':'Collapse',
		'ConfigMap':'Config Map',
		'inputConfigPath':'please input config path',
		'inputConfigValue':'please input config value',
		'inputConfigName':'please input config file name',
		'fillInInitialDelaySeconds':'initial delay second(s)',
		'fillInTimeoutSeconds':'timeout second(s)',
		'fillInPeriodSeconds':'interval second(s)',
		'fillInSuccessThreshold':'success threshold',
		'fillInFailureThreshold':'failure threshold',


		//modifyRouter page
		'modifyRouter':'Modify Gateway',
		'annotation':'Annotation',

		//monitorChart page
		'container':'Container',
		'time':'Time',
		'thirtyMinute':'last 30 minutes',
		'sixHour':'last 6 hours',
		'twentyFourHour':'last 24 hours',
		'sevenDay':'last 7 days',
		'thirtyDay':'last 30 days',
		'setupToNow':'since creation',
		'createMonitor':'creating monitor chart, please wait...',
		'process':'Process',

		//newIng page
		'Httprouter':'HTTP Gateway',
		'Tcprouter':'TCP Gateway',
		'newProxy':'Add Proxy',
		'addTCPRouter':'Create TCP Gateway',
		'addHTTPRouter':'Create HTTP Gateway',
		'fillInName':'please fill in name',
		'fillInNamespace':'please fill in project',
		'hostName':'Domain',
		'HostName':'Host Name',
		'chooseService':'Service',
		'targetService':'Target Service',
		'saveProxy':'Create',
		'fillInPath':'fill in path,eg: /filename',
		'urlMap':'URL Mapping',
		'subDomain':'Name',
		'domain':'Domain',

		//newLb page
		'fillInPicker':'please fill in picker',
		'portRange':'port range(20000-20670)',
		'protocolType':'Protocol Type',
		'selector':'Node Selector',
		'portMap':'Port Mapping',


		//podContainer page
		'refreshConfig':"Update",
		'runState':'State',
		'containerState':'Container State',
		'containerRestart':'Container Restart Count',
		'restartTime':'Restart Count',
		'readOnlyYes':'Yes',
		'readOnlyNo':'No',
		'log':'Log',
		'storagePath':'Path',
		'wrongPath':'wrong path format',
		'gitUrl':'Git Url',

		//podInformation page
		'activeTime':'Start Time',
		'podActiveTime': 'Create Time',
		'containerCount':'Container',
		'IP':'IP',
		'nodeIP':'Node IP',
		'creationTime':'Creation Time',

		//podInstance page
		'Pods':'Pods',
		'internelIP':'Internal IP',
		'podClusterIP':'Service IP',
		'internalDomain':'Service Domain',
		'podIP':'Pod IP',
		'running':'Running',
		'pause':'Pause',

		//serviceDetail page
		'autoflex':'Autoscaling',
		'terminating':'Terminated',
		'waiting':'Waiting',
		'VolumeMounts':'Vol Mounts',
		'pod':'Pod',
		'ChangeConfigValue':'Change Config Value',
		// 'EditValue':'Edit Value',

		//serviceInformation page
		'refershTime':'Last Update',
		'internelPort':'Port',
		'Owner':'Owner',
		'Version': 'Version',
		'ContainerStatus':'Container Status',
		'Specs':'Container Specs',
		'configName':'File Name',
		'configValue':'File Value',

		//serviceNew page
		'newService':'Add Service',
		'serviceName':'Name',
		'fillInServiceName':'please fill in service name',
		'wrongServiceName':'service name illegal',
		'labelText':'please input label as aaa=bb,cc=ddd format',
		'wrongLabel':'label illegal',
		'session':'Session',
		'containerList':'Container',
		'config':'Config',
		'add':'Add',
		'fillInInternelIP':'please fill in service IP',
		'wrongIP':'IP Illegal',
		'saveService':'Save',
		'inputSelectorKey':'input the key of selector',
		'inputSelectorValue':'input the value of selector',

		//warninglist page
		'related':'Related',

		//setting page
		'username':'User ID',
		'password':'Password',
		'serviceAndPod':'Service/Pod',
		'deleting':'deleting...',
		'creating':'creating...',
		'modifypassword':'Change Password',

		//storageDetail page
		'serviceHost':'Service IP',
		'newStorage':'Add Volume',
		'storageName':'Name',
		'saveStorage':'Save',
		'fillInStorageName':'please fill in volume name',
		'wrongStorageName':'volume name illegal',
		'path':'Path',

		//imageAll page 
		'downAndUpload':'Upload & Download',
		'author':'Author',
		'loading':'loading...',
		'deployImage': 'click to deploy the image',

		//upload page
		'downloadImage':'Download Image',
		'downloadStep1':'In local docker environment input the following commands, then you can pull an image to your local repository.',
		'downloadStep2':'Notice：For your convenience, you can change the tag to short label after download,for example:',
		'pushImage':'Release Image',
		'stepOne':'1. In local environment input the following commands to login.',
		'stepTwo':'2. If you already had an image that want to pushed,for example its named hello-world.Otherwise you don\'t have an image,you can pull one on Docker official websit first.',
		'stepThree':'3. And then,we need to tag this image, input commands: ',
		'stepFour':'4. Finally input the following commands in console,and then you can push this image to your own image repository.',
		'repository':'self-define repository',

		//editInstance page
		'inputInstance':'please fill in instance',
		'instanceMustNumber':'instance must be number',
		'instanceMustLagerOne':'instance must lager than 1',

		//podDetaileController psge
		'BasicInfo':'Basic Info',
		'AdvanceInfo':'Advance Info',
		'basicInformation':'Service Overview',
		'podInformation':'Pod Overview',
		'monitor':'Monitoring',
		'podInstance':'Pod',
		'event':'Event',
		'logInformation':'Log Overview',
		'logdir':'Log File',

		//myTenant page
		'basicTanInformation':'MyTenant Overview',
		'namespaceInformation':'Project Overview',
		'roleInformation':'Role Overview',
		'networkInformation':'Network Overview',
		'harborInformation':'Repo Group Overview',
		'adminInformation':'Administrator Overview',
		'tenantname':'TenantName',
		'deletemessage':'Are You Sure To Delete?',
		'mytenantname':'Tenant Name',
		'mytenantadmin':'Tenant Admin',
		'comment':'Comment',
		'adminsname':'Admin Name',
		'addtime':'Add Time',
		'harborname':'Repo Group',
		'harbortype':'Repo Group Type',
		'namespacename':'Project Name',
		'networkname':'Network Name',

		//confirm related
		'serviceError':'service exception',
		'serviceErrorText':'service exception，please try again later！',
		'inputError':'input error',
		'inputCommand':'please input command',
		'inputArgs':'please input args',
		'inputEnv':'please input environment variable',
		'inputStorage':'please input volume',
		'storageDuplicate':'duplicate volume path',
		'atLeastOnPort':'please input at least on port config',
		'nameDuplicate':'multiple name error',
		'conatinerNameDuplicate':'this container has same name with other container',
		'serviceNameDuplicate':'this service has same name with other service in this project',
		'noServiceError':'haven\'t choose service',
		'selectServiceError':'please choose service',
		'giveUpService':'Sure To Give Up Create Service?',
		'giveUpConfig':'Sure To Give Up Config?',

		'namespaceDuplicate':'multiple project',
		'userDuplicate':'multiple user name',

		'newFail':'creat fail',
		'inputNamespace':'please input project',
		'deleteNamespaceService':'please delete service of this project and try again later',
		'deleteFail':'delete fail',

		'noStorageError':'haven\'t choose volume',
		'selectStorageError':'please choose volume',
		'storageNameDuplicate':'this volume has same name with other volume in this project',

		'hostaddress':'Entrance Domain：',
		'entranceip':'Entrance IP：',

		//node
		'harborList':'Repo Group List',
		'tenantName':'Teanant Name',
		'networkList':'Network List',
		'Internal Virtual Port':'Service Port',
		'Service Port':'Service Port',
		'virtualPort': 'Virtual Port',
		'podPort': 'Pod Port',
		'containerPort': 'Container Port',
		'Success':'Success',
		'Label Edit Success':'Label Editing Success!',
		'Error':'Error',
		'inputLabelKey':'input key of label',
		'inputLabelValue':'input value of label',
		'nodeInfo':'Node Info',
		'Ready':'Ready',
		'OutOfDisk':'Out Of Disk',
		'MemoryPressure':'Memory Pressure',

		'livenessProbe': 'Liveness Probe',
		'readinessProbe': 'Readiness Probe',
		'fillInProbe': 'please fill in probe',
		'PodStatus':'Pod Status',
		'architecture':'Architecture',
		'os':'OS',
		'kernelVersion':'Kernel Version',
		'kubeProxyVersion':'kube-proxy Version',
		'kubeletVersion':'kubelet Version',
		//network
		'createNetwork':'Create Network',
		'networkName':'Name',
		'subnet':'Subnets',
		'noNetworkError':'Network was not select',
		'selectNetworkError':'Please select the network to delete',
		'noHarborError':'Repo Group was not select',
		'selectHarborError':'Please select the Repo Group to delete',
		'noVolumeError':'Volume was not select',
		'selectVolumeError':'Please select the volume to delete',
		'netname':'Name',
		'Subname':'Sub Name',
		'subbind':'Sub Binding',

		// user Authorization
		'userAuthorization': 'Authorization',
		'role':'Role',
		'roleBinding':'RoleBinding',
		'clusterRoleBinding':'Cluster RoleBinding',
		'type':'Type',
		'bindingCount':'Binding Count',
		'newRole':'Add Role',
		'newCrole':'Add Cluster Role',
		'resource':'Resource',
		'noneResource':'None Resource',
		'saveRole':'Save',
		'user':'user',
		'clusterrole': 'Cluster Role',
		'clusterroleBinding': 'Cluster RoleBinding',
		'newRoleBinding':'add RoleBinding',
		'newCRoleBinding':'add Cluster RoleBinding',
		'source':'Source',
		'priority':'Priority',

		//menu
		'Overview':'Overview',
		'Dashboard':'Dashboard',
		'Rolebinding':'Role Binding',
		'Application':'Application',
		'UserManage':'User Management',
		'Usermanage':'User',
		'OperationAudit':'Audit',
		'Tenet':'Tenant Management',
		'Tenetmanage':'Tenant',
		'Mytenet':'My Tenant',
		'Myproject':'My Project',
		'Authorize':'Authorization',
		'Role':'Role',
		'Rolebinding':'Role Binding',
		'Softinfrastructure':'Infrastructure',
		'Menunode':'Node',
		'Project':'Project',
		'Menunetwork':'Network',
		'Menuharbor':'Repo Group',
		'Cloudplatform':'Cloud Platform',
		'Component':'Component',
		'KubeProxy':'KubeProxy',
		'Scheduler':'Scheduler',
		'Ctrlmanage':'Controller Management',
		'Apiserver':'Api Server',
		'Kubelet':'Kubelet',
		'Docker':'Docker',
		'Etcd':'Etcd',
		'Extension':'Extension',
		'Influxdb':'InfluxDB',
		'Harbor':'Harbor',
		'Elasticsearch':'Elastic Search',
		'HAproxy':'HAproxy',
		'Initial':'Initialize',

		//tenant
		'Tenantname':'Tenant Name',
		'Tenantlist':'Tenant List',
		'Admin':'Admin',
		'tenantInformation':'Tenant Overview',
		'Network':'Network',
		'Harbor':'Repo Group',
		'Volume':'Storage',
		'Member':'Member',
		'Networkname':'Name',
		'Harborname':'Name',
		'Volumename':'Name',
		'Username':'User Name',
		'RealName':'Real Name',
		'Add User To Tenant':'Add User',
		'Create Volume For Tenant':'Create Volume',
		'Create Repo Group For Tenant':'Create Repo Group',
		'Add Tenant':'Create Tenant',
		'NetworkCount':'Network Count',
		'ProjectCount':'Project Count',
		'RepoGroupCount':'Repo Group Count',
		'Project Overview':'Project Overview',
		'By Service':'Service Distribution',
		'By Member':' Member Distribution',
		'Edit':'Edit',
		'tenantResource':'Resource',


		//project 
		'projectInformation':'Project Overview',
		'CreateProject':'Create Project',
		'BasicConfig':'Basic Config',
		'Subnet':'Subnet',
		'ResourceQuota':'Resource Quota',
		'ChangeProject':'Change Project',
		'HarborMember':'Repo Group Members',

		'Multiple':'Multiple',
		'Usage':'Usage',
		'Provider':'Provider',
		'readOnlyTrue':'true',
		'readOnlyFalse':'false',
		'Add User To Project':'Add User To Project',
		'Add User To Repo Group':'Add User To Repo Group',

		'subnetName':'Sub Name',
		'addsubnet':'Add Subnet',

		//tenant module error text
		'fillInTenantName':'Please fill in Tenant Name',
		'wrongTenantName':'Tenant Name Illegal',
		'fillInNetworkName':'Please fill in Network Name',
		'wrongNetworkName':'Network Name Inllegal',
		'fillInProjectName':'Please fill in Project Name',
		'wrongProjectName':'Project Name Inllegal',
		'fillInHarborName':'Please fill in Repo Group Name',
		'wrongHarborName':'Repo Group Name Illegal',
		'fillInVolumeName':'Please fill in Volume Name',
		'wrongVolumeName':'Volume Name Inllegal',

		//harbor and repo and tag
		'total':'Total',
		'insecurity':'Insecure',
		'mild':'Mild',
		'security':'Secure',
		'not support':'Not Support',
		'abnormal':'Abnormal',
		'high':'High Risk Vulnerabilitles',
		'other':'Other Risk Vulnerabilitles',
		'package':'Package',
		'vulnerability':'Vulnerability',
		'VulnerabilitleName':'Vulnerabilitle Name',
		'PackageName':'Package Name',
		'PackageVersion':'Package Version',
		'HighLevel':'High Risk',
		'MediumLevel':'Medium Risk',
		'LowLevel':'Low Risk',
		'NegligibleLevel':'Negligible Risk',
		'UnknowLevel':'Unknow',
		'Level':'Risk Level',
		'CurrentVersion':'Current Version',
		'FixedVersion':'Repaired Version',
		'ImageLayer':'Image Layer',
		'imageAnalyze':'Image Vulnerabilitles Analyze',
		'Total Number of Vulnerabilitles':'Total Number Of Vulnerabilitles',
		'Vulnerabilitles can be Repaired':'Vulnerabilitles Can Be Repaired',
		'Number of High Risk vulnerabilitle(s)':'High Risk Vulnerabilitle(s)',
		'Number of Medium Risk vulnerabilitle(s)':'Medium Risk Vulnerabilitle(s)',
		'Number of Low Risk vulnerabilitle(s)':'Low Risk Vulnerabilitle(s)',
		'Number of Negligible Risk vulnerabilitle(s)':'Negligible Risk Vulnerabilitle(s)',
		'Number of Unknow vulnerabilitle(s)':'Unknow Vulnerabilitle(s)',
		'can be repaired':'can be repaired',
		'no repo':'No Repo For Now',

		//user
		'fillInEmailName':'please fill in email',
		'wrongEmailName':'email is illegal',
		'fillInUserName':'please fill in users name',
		'wrongUserName':'user name is illegal',
		'userNameDuplicate':'the user is already exists',
		'emailDuplicate':'multiple email error',
		'EmailDuplicate':'the email is already exists',
		'noUserError':'No user was selected!',
		'selectUserError':'Please select at least one user!',
		'fillInPassword':'Incorrect password',
		'wrongPassword':'The password must contain both uppercase and lowercase letters and numbers!',
		'wrongPasswordLength':'Password length must be greater than 7!',
		'fillPassword':'Password length',
		'WrongPassword':'Passwords can not contain special characters',
		'addUser':'Add User',


		//extend
		'monitorProviderList':'Monitor Provider',
		'imageProviderList':'Repo Provider',
		'logProviderList':'Log Provider',
		'loadBalancerProviderList':'Load Balancer Provider',
		'storageProviderList':'Storage Provider',
		'networkProviderList':'Network Provider',
		'ClusterComponentList':'Cluster Component',
		'address':'Address',
		'host':'Host Name',
		'lastUpdateTime':'Last Update',
		'logmessageon':'The log alarm is on',
		'logmessageoff':'Log alarm is not enabled',
		'monitoron':'Monitoring Alarms are turned on',
		'monitoroff':'The monitoring alarm is not on',
		'goset':'Go Set',
		'gooppen':'Go Open',
		'isLogMonit':'LogMonitor',
		'logMonitSeverity':'LogMonitorSeverity',
		'restartMonit':'RestartMonit',
		'alarmType':'AlarmType',
		'alarmRules':'Alarm Rules',
		'alarmSetting':'Alarm Setting',
		'measurement':'Measurement',
		'threshold':'Threshold',
		'Actions':'Actions',
		'logboth':'Warnings and error logs',
		'onglog':'Error log only',
		'SMTPServer':'SMTPServer',

		//infras
		'LogWarningTurnedOn':'Log Alarms Turned On',
		'LogWarningClosed':'Log Alarms Closed',
		'goConfig':'Config',
		'goOpen':'Open',
		'MonitorAlarmsTurnedOn':'Monitor Alarms Turned On',
		'MonitorAlarmsClosed':'Monitor Alarms Closed',
		'nodeList':'Node List',
		'ConfigLogAlarm':'Config Log Alarm',
		'OpenLogAlarm':'Open Log Alarm',
		'OpenLogMonitor':'Open Log Monitor',
		'ConfigLogMonitor':'Config Log Monitor',

		// Dashboard page
		'CPU':'CPU',
		'Memory':'Memory',
		'Coworkers':'Coworkers',
		'DeploymentCountByUser':'Service Count By User',
		'DeploymentCount':'Service Count',
		'Secure Image Count':'Secure Image Count',
		'Abnormal Image Count':'Abnormal Image Count',
		'Total Image Count':'Total Image Count',
		'Insecure Image Count':'Insecure Image Count',
		'Un-scannable Image Count':'Un-scannable Image',
		'Image Count By User':'Image Count By User',
		'Insecure Image Count By User':'Insecure Image Count By User',
		'System Warning':'System Warning',
		'Recent Events':'Recent Events',
		'Pod Usage':'Pod Usage',
		'CPU Usage':'CPU Usage',
		'Memory Usage':'Memory Usage',
		'Disk Usage':'Disk Usage',
		'Current Usage':'Current Usage',
		'Can Be Created':'Can Be Created',
		'Kubernetes Version':'Kubernetes Version',	
		'ETCD Version':'ETCD Version',
		'Docker Version':'Docker Version',
		'Neutron Version':'Neutron Version',
		'Calico Version':'Calico Version',
		'Infrastructure':'Infrastructure',
		'Host':'Host',
		'CPU Core':'CPU Core',
		'System Component Status':'System Component Status',
		'Tenants':'Tenants',
		'Tenant Project Usage Rate':'Tenant Project Usage',
		'Tenant Image Usage Rate':'Tenant Image Usage',
		'Can be Used':'Can be Used',
		'In this Project':'In this Project',

		//log
		'output':'Standard output',
		'logout':'Log output',
		'logOutput':'Log Source',

		//user audit
		'userAudit':'USER AUDIT',
		'operation':'Operation',
		'module':'Module',
		'params':'Params',
		'accessTime':'Time',
		'url':'URL',
		'accessUser':'User',
		'accessNamespace':'Project',
		'accessTenantName':'Tenant',
		'search':'Search',
		
		//initial
		'Admin Initial':'Admin',
		'Cluster Role Initial':'Cluster Role',
		'Machine Account Initial':'Machine Account',
		'Reset To Default':'Reset To Default',
	});

	$translateProvider.preferredLanguage('en');
}])